### ISSUE TITLE
PBIX files with example/demo data in them

### ISSUE THREAD

**Issue by mhammons** [Microsoft/BusinessPlatformApps#1095]
Hello,

It sure would be helpful/beneficial to have a PBIX file with demo data already loaded in them. Customers need to be able to better visualize what's available and in the ealry stages of an implementation there is very little data for these empty pbix files to be useful.

Thank you.

**Comment by yashti** [comment]
In App Source when browsing the solution templates you can click "Test Drive" to test it out with example data:

https://appsource.microsoft.com/en-us/product/web-apps/microsoft-powerbi.pbisolntemplate_cmpgnbrandmgnt_twitter?tab=Overview
