### ISSUE TITLE
Azure IoT Central Analytics solution template doesn't exist on appsource

### ISSUE THREAD

**Issue by ph-jo** [Microsoft/BusinessPlatformApps#1154]
All the links to Azure IoT Central Analytics solution template are dead. The links to appsource are also dead, looks like it's been removed.

**Comment by expiscornovus** [comment]
I agree, I have the same thing with the Dynamics 365 PSA PowerBI template solution.

**Comment by ph-jo** [comment]
@expiscornovus They've added the IoT Central Analytics solution again recently. I'm marking this as closed.
