### ISSUE TITLE
Microsoft SCCM Template - Compile

### ISSUE THREAD

**Issue by JordanTheITGuy** [microsoft/BusinessPlatformApps#1155]
The original SCCM template provided a .EXE installer that used the files to generate the required stored procedures. I've yet to figure out how the .SLN in the root of the gitrepository is supposed to be used to compile the .EXE for this specific template. 

Ideally the instructions for the GitHub should include how to compile the .EXE (if its even possible from the current code base). 

The current instructions just show how to run a .EXE that doesn't exist and there doesn't seem to be a clear path to compile those .EXE's

**Comment by tstolswo** [comment]
I opened a premier support case on the matter and was directed to open an issue here, after weeks of back and forth about how the installation instructions are not valid when an installer is not present.

**Comment by ml58158** [comment]
I am in the same boat..

I have an older version of the installer but it no longer works.

**Comment by ml58158** [comment]
The biggest difference between the github version and the exe version, is the github version does not setup access to a secondary DB to store PowerBI data.

Previously, PowerBI will copy data from the SCCM DB to a 2nd DB and pull the data from that DB.

Now, there is not a way to do that....that I have found.

**Comment by JordanTheITGuy** [comment]
If I was to start a project and I'm not saying I will - using a fork of this GitHub and created a powershell script/app that did what the old install binary did would it be helpful? I'll retweet this thread on Twitter as well to see if that causes the .EXE to show up and if it doesn't I'll consider making my own solution that works with the template.

**Comment by tstolswo** [comment]
If Microsoft isn't committed to support this, yeah - I think a community solution would be greatly useful. Please let me know if you can think of anything I can do to help, if it's testing or whatever. I'd be glad to contribute in any way I can.

**Comment by JordanTheITGuy** [comment]
> The biggest difference between the github version and the exe version, is the github version does not setup access to a secondary DB to store PowerBI data.
> 
> Previously, PowerBI will copy data from the SCCM DB to a 2nd DB and pull the data from that DB.
> 
> Now, there is not a way to do that....that I have found.

I have two copies of the intstaller ;) two different versions I have thought about uploading 'somewhere' to allow people to download it. I even considered publishing it on TechNet.

**Comment by JordanTheITGuy** [comment]
> If Microsoft isn't committed to support this, yeah - I think a community solution would be greatly useful. Please let me know if you can think of anything I can do to help, if it's testing or whatever. I'd be glad to contribute in any way I can.

I think it could be a unique oppurtunity because of the ability to interact with the DataBase - something we normally don't do because we are not supposed to. If I can get someone at microsoft to say that - yes if I create a script to create all the views etc in a report Server DB and I won't get smacked for breaking support I think I'll do it.

**Comment by JordanTheITGuy** [comment]
Looks like they uploaded the latest version of the compiled solution template :)
