### ISSUE TITLE
Under what license is the Twitter Template Released?

### ISSUE THREAD

**Issue by cdtdev** [Microsoft/BusinessPlatformApps#166]
Hi, I tried to search and find out what license the Twitter Template is released under?

https://github.com/Microsoft/BusinessPlatformApps/tree/master/Source/Apps/Microsoft/Released/Microsoft-TwitterTemplate

Thanks
Chris

**Comment by MohaaliMicrosoft** [comment]
Hey Chris,

Are you referring to the template or the underlying components or the source code just to be clear ?

**Comment by cdtdev** [comment]
Template and source code.

**Comment by jeffwilcox** [comment]
Shouldn't this repository also have a `LICENSE`?

**Comment by MohaaliMicrosoft** [comment]
Thanks for reporting this. will add it in
