### ISSUE TITLE
[tempuserview] join causes duplication due to version-tracking

### ISSUE THREAD

**Issue by dprtsk** [Microsoft/BusinessPlatformApps#665]
[dbo].[systemusermanagermap] can contain multiple user-manager mappings for the same user [Id], with different values in [VersionNumber].

Since [smgt].[tempuserview] contains a simple outer join to [dbo].[systemusermanagermap], this can create multiple records in the resulting [User] Query in PBI, which dissatisfies the model's relationship constraints and fails the refresh with the following message: 

> Column 'User Id' in Table 'User' contains a duplicate value 'D22C22DE-F7E5-E511-810A-3863BB354C10' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.

IMO the fix is to constrain the join with a subselect to the latest record in the version history.

**Comment by richtk** [comment]
Thanks. Working on this now.

**Comment by dprtsk** [comment]
My workaround was to add this to the subselect:

`,ROW_NUMBER() OVER(PARTITION BY dbo.systemuser.systemuserid ORDER BY dbo.systemusermanagermap.versionnumber asc) as rank`

And this in the where-clause:
`AND a.rank = 1`
