### ISSUE TITLE
deploy Private Assembly to Function is failing

### ISSUE THREAD

**Issue by ministainer** [Microsoft/BusinessPlatformApps#704]
Hi there,

I'm trying to run the solution template code locally, however, it fails while deploying Microsoft-NewsTemplate in the action
`displayname": "$translate(INIT_ACTION_DEPLOYING_NEWS_ASSETS)",
                "name": "Microsoft-DeployPrivateAssemblyToFunction"` as the file below cannot be found.
Microsoft.KnowledgeMining.MainArticleExtractor.dll

do we have access to above dll ?

**Comment by MohaaliMicrosoft** [comment]
Hey, if you deploy the template from prod you should be able to get access to the DLL. as the DLL is private we were not allowed to put it inside Github.

Sorry for the super late response

**Comment by ministainer** [comment]
yup it's working but I can't run it locally , do you have a Microsoft link for the DLL  or it can't be shared at all ?

**Comment by yashti** [comment]
Unfortunately we are unable to provide that .DLL, sorry

**Comment by ministainer** [comment]
@yashti, so what is the purpose of open sourcing this project !
